server:
  port:8001

#mybatis配置
mybatis:
  type-aliases-package: pojo.Dept
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true #驼峰转数据库的横线

#Spring的配置
spring:
  application:
    name: spring-cloud-provider-dept-8001
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver  #设置数据源
    url: jdbc:mysql//localhost:3306/jdbc?userUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
